Added live stream examples
bitmovin/bitmovin-java pull request #12
Opened 2017-11-27 22:09 UTC by gfronza

2017-11-28 09:47 UTC, Tigraine approved these changes
LGTM

2017-11-28 09:48 UTC, rkersche requested changes
Nice, please just move all `{` into the next line

2017-11-28 09:48 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateAndStartLiveStreamWithVP9.java
> +		for (VideoProfile videoProfile : VIDEO_ENCODING_PROFILES) {
`{` goes in next line

2017-11-28 14:21 UTC, gfronza commented
@rkersche Fixed the `{` position. Already changed my editor's code style :)

2017-11-29 08:33 UTC, rkersche requested changes

2017-11-29 08:33 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateAndStartLiveStreamWithVP9.java
> +		videoConfig.setId(String.format("vp9_%dp", videoProfile.height));
IDs are read-only

2017-12-01 11:23 UTC, gfronza commented
@rkersche I removed the `setId` call. Should be fine now.

2017-12-01 11:30 UTC, rkersche approved these changes

2017-12-06 14:03 UTC, merged