Added multi-codec example
bitmovin/bitmovin-java pull request #14
Opened 2017-12-14 02:20 UTC by gfronza

2017-12-17 21:03 UTC, rkersche requested changes
Cool, please also send me some examples for DASH and HLS

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +			case DASH: manifestsToStart.add(createDashManifest(encoding, output)); break;
case needs to be indented. manifestToStart and break go in the next line

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +			case HLS: manifestsToStart.add(createHlsManifest(encoding, output)); break;
Same here

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +			        audioMediaInfo.setType(MediaInfoType.AUDIO);
Indent

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +			        audioMediaInfo.setName(audioProfile.language);
Indent

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +		{
Incorrect indention

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +	    		{
Incorrect indention

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +    {
Incorrect indention

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +	private VideoProfile[] reverseList(VideoProfile[] videoEncodingProfiles)
Please use `ArrayUtils.reverse` from 
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/ArrayUtils.html

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +    {
Incorrect indention

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +        MuxingStream list = new MuxingStream();
Incorrect indention

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +        MuxingStream list = new MuxingStream();
Incorrect indention

2017-12-17 21:03 UTC, rkersche commented on src/test/java/com/bitmovin/api/examples/CreateMultiCodecEncodingWithDashHls.java
> +        public InvalidCodecException(String msg)
Incorrect indention

2017-12-18 11:39 UTC, gfronza commented
@rkersche Thanks! I guess I forgot to run the auto format because my Eclipse is configured properly.

Examples (HLS and DASH):
[manifests.zip](https://github.com/bitmovin/bitmovin-java/files/1567712/manifests.zip)

2017-12-18 16:51 UTC, rkersche approved these changes

2017-12-18 17:00 UTC, merged