Added MJPEG codec configuration and MOV muxing support
bitmovin/bitmovin-java pull request #17
Opened 2018-02-16 13:30 UTC by moser4035

2018-02-20 15:31 UTC, msmole requested changes

2018-02-20 15:31 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreateMp4AndMovEncoding.java
> +    public void testCreateMp4AndMovEncoding() throws URISyntaxException, BitmovinApiException, UnirestException, IOException, RestException, InterruptedException
I think it would be good to rename the test to something containing keyframe archive.

2018-02-20 15:31 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreateMp4AndMovEncoding.java
> +            System.out.println("Encoding has status error");
A return is missing. Otherwise the success message will be shown as well.

2018-02-20 15:31 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreateMp4AndMovEncoding.java
> +        if (status.getStatus() != Status.FINISHED)
I think it is more readable if you check for ERROR here.

2018-02-21 08:44 UTC, rkersche approved these changes

2018-02-21 08:45 UTC, msmole approved these changes

2018-02-21 08:46 UTC, merged