Feature/add av1 video codec
bitmovin/bitmovin-java pull request #52
Opened 2018-08-16 13:29 UTC by alodijutgla

Creation of the feature branch _add_AV1_VideoCodec_ in order to add the AV1 codec configurations to the encoding configurations.

2018-08-16 14:55 UTC, ChristianFeldmann requested changes
Don't we have to add AV1 also to the bitmovin-java/src/main/java/com/bitmovin/api/encoding/codecConfigurations/enums/ConfigType.java file? Or is this part of something else?

2018-08-16 15:29 UTC, msmole requested changes

2018-08-16 15:29 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/AV1VideoConfiguration.java
> +import com.bitmovin.api.encoding.codecConfigurations.enums.*;
Do not use * imports.

2018-08-16 15:29 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/enums/AV1KeyPlacementMode.java
> +
remove empty line

2018-08-16 15:29 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/AV1VideoConfiguration.java
> +/**
Remove all header comments.

2018-08-16 15:29 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/enums/AV1AdaptiveQuantMode.java
> +/**
Remove

2018-08-16 15:29 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/enums/AV1KeyPlacementMode.java
> +/**
Remove

2018-08-17 08:13 UTC, ChristianFeldmann approved these changes

2018-08-20 06:16 UTC, msmole requested changes

2018-08-20 06:16 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/AV1VideoConfiguration.java
> +public class AV1VideoConfiguration extends VideoConfiguration {
`{` in next line.

2018-08-20 06:16 UTC, msmole commented on src/main/java/com/bitmovin/api/encoding/codecConfigurations/AV1VideoConfiguration.java
> +    public Integer getLagInFrames() { return this.lagInFrames; }
Please write getters and setters not as one-liner.
`{` always on a new line. After that the statement, and then the `}` on a new line again.

2018-08-20 09:18 UTC, msmole approved these changes

2018-08-20 13:20 UTC, merged