Added per title encoding example
bitmovin/bitmovin-java pull request #55
Opened 2018-08-22 15:16 UTC by moser4035

2018-08-23 05:59 UTC, SandroLinder requested changes

2018-08-23 05:59 UTC, SandroLinder commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +    private static String OUTPUT_BASE_PATH = "output/bitmovin-java/per-title-encoding-example/";
change this to path/to/output/

2018-08-23 05:59 UTC, SandroLinder commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        videoConfiguration = bitmovinApi.configuration.videoH264.create(videoConfiguration);
duplicate

2018-08-23 05:59 UTC, SandroLinder commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        List<Stream> perTitleResultStreams = bitmovinApi.encoding.stream.getStreams(encoding);
will always be greater than 0 because the per title templates are also retrieved

2018-08-23 05:59 UTC, SandroLinder commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        Assert.assertTrue(perTitleResultStreams.size() > 0);
remove asserts. Check with if and give appropriate message

2018-08-23 09:08 UTC, rkersche approved these changes

2018-08-23 10:47 UTC, SandroLinder approved these changes

2018-08-24 05:39 UTC, seburgi approved these changes

2018-08-28 09:38 UTC, msmole requested changes

2018-08-28 09:38 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        encoding.setEncoderVersion("BETA");
should probably be stable?

2018-08-28 09:38 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        autoRepresentation.setAdoptConfigurationThreshold(0.3);
why 0.3 and not the default 0.5?

2018-08-28 09:38 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        dashManifest.setName("perTitleManifest.mpd");
simply stream.mpd or manifest.mpd

2018-08-28 09:38 UTC, msmole commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +                    String.format("video/%s/", h264VideoConfiguration.getBitrate())
Don't we get the chosen output path back from the stream and muxing that get generated for per-title? This seems strange to do it like this.

2018-08-28 11:06 UTC, moser4035 commented on src/test/java/com/bitmovin/api/examples/CreatePerTitleEncoding.java
> +        encoding.setEncoderVersion("BETA");
ATM this has to be BETA

2018-08-28 11:08 UTC, msmole approved these changes

2018-08-28 11:09 UTC, merged