Feature/multi tenant api
bitmovin/bitmovin-java pull request #60
Opened 2018-09-05 18:31 UTC by rfliam

2018-09-05 18:39 UTC, jamescyeh approved these changes
One minor change, otherwise LGTM.

2018-09-05 18:39 UTC, jamescyeh commented on src/test/java/com/bitmovin/api/examples/MultiTenantEncoding.java
> + * Created by Roland Kersche on 01.06.17.
Ahem

2018-09-06 13:38 UTC, dominic-miglar requested changes

2018-09-06 13:38 UTC, dominic-miglar commented on src/main/java/com/bitmovin/api/BitmovinApi.java
> +        if (this.tenantID != null) {
code style -> { goes to next line.

2018-09-06 13:38 UTC, dominic-miglar commented on src/test/java/com/bitmovin/api/examples/MultiTenantEncoding.java
> +    private AudioAdaptationSet addAudioAdaptationSet(DashManifest manifest, Period period, AudioAdaptationSet audioAdaptationSet)
is this method even used?

2018-09-06 18:06 UTC, rfliam commented
Changes made re-feedback.  Please re-review asap @dominic-miglar @jamescyeh .

2018-09-11 12:04 UTC, rfliam commented
Ping. @dominic-miglar

2018-09-12 13:15 UTC, dominic-miglar approved these changes

2018-09-12 14:00 UTC, rkersche requested changes

2018-09-12 14:00 UTC, rkersche commented on README.md
> +      <version>1.37.0</version>
That will be changed during a release

2018-09-12 14:00 UTC, rkersche commented on pom.xml
> +    <version>1.37.0</version>
That will be changed during a release

2018-09-12 14:00 UTC, rkersche commented on src/main/java/com/bitmovin/api/BitmovinApi.java
> +    private static String DEFAULT_X_API_CLIENT_VERSION = "1.37.0";
That will be changed during a release

2018-10-01 19:50 UTC, rfliam commented
This is still outstanding.

2018-10-08 13:23 UTC, rkersche approved these changes

2018-10-19 16:27 UTC, merged