Fixing InterlaceMode naming conventions
bitmovin/bitmovin-java pull request #75
Opened 2018-11-20 13:20 UTC by wabiloo

2018-11-20 16:04 UTC, jamescyeh requested changes
two minor changes

2018-11-20 16:04 UTC, jamescyeh commented on src/main/java/com/bitmovin/api/encoding/filters/InterlaceFilter.java
> +    public InterlaceMode getInterleaveMode()
```suggestion
    public InterlaceMode getInterlaceMode()
```

2018-11-20 16:04 UTC, jamescyeh commented on src/main/java/com/bitmovin/api/encoding/filters/InterlaceFilter.java
> +    public void setInterleaveMode(InterlaceMode mode)
```suggestion
    public void setInterlaceMode(InterlaceMode mode)
```

2018-11-20 18:06 UTC, wabiloo reviewed
Yep, makes sense

2018-11-28 15:28 UTC, rkersche approved these changes

2018-11-28 15:28 UTC, merged